version: '3'
services:
  spark-test:
    restart: always
    container_name: spark-test
    network_mode: bridge
    build: ./
    command: pyspark
    stdin_open: true
    tty: true
    working_dir: /home/sparkuser/notebooks
    volumes:
      - ./scripts:/home/sparkuser/scripts
      - ./notebooks:/home/sparkuser/notebooks
      - ./.jupyter:/home/sparkuser/.jupyter
      - ./.aws:/home/sparkuser/.aws
      - ./certbot/conf:/etc/letsencrypt
    ports:
      - "9999:9999"
    env_file:
      - .env
  nginx:
    image: nginx:1.15-alpine
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx-log:/var/log/nginx/
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"
    stdin_open: true
    tty: true
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    network_mode: bridge
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"